package alphabets

var Spanish = Alphabet{
	"desc": "Spanish",
	"-":    "Dash",
	".":    "Point",
	"a":    "Antonio",
	"b":    "Barcelona",
	"c":    "Carmen",
	"ch":   "Chocolate",
	"d":    "Dolores",
	"e":    "Enrique",
	"f":    "Francia",
	"g":    "Gerona",
	"h":    "Historia",
	"i":    "Inés",
	"j":    "José",
	"k":    "Kilo",
	"l":    "Lorenzo",
	"m":    "Madrid",
	"n":    "Navarra",
	"ñ":    "Ñoño",
	"o":    "Oviedo",
	"p":    "París",
	"q":    "Querido",
	"r":    "Ramón",
	"s":    "Sábado",
	"t":    "Tarragona",
	"u":    "Ulises",
	"v":    "Valencia",
	"w":    "Washington",
	"x":    "Xiquena",
	"y":    "Yegua",
	"z":    "Zaragoza",
}
